// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB24LKrdGn6phkDuuB7tAGrH_iX-t3Qn7M',
    appId: '1:125810430014:web:824a273ad5695d932fc16f',
    messagingSenderId: '125810430014',
    projectId: 'ainews-f6d83',
    authDomain: 'ainews-f6d83.firebaseapp.com',
    storageBucket: 'ainews-f6d83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFFjeDC2x_Sjo5SOmpF36YHRZ7DfQkzc',
    appId: '1:125810430014:android:3dc6e63113487c1f2fc16f',
    messagingSenderId: '125810430014',
    projectId: 'ainews-f6d83',
    storageBucket: 'ainews-f6d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB24LKrdGn6phkDuuB7tAGrH_iX-t3Qn7M',
    appId: '1:125810430014:web:824a273ad5695d932fc16f', // TODO: Update with iOS App ID
    messagingSenderId: '125810430014',
    projectId: 'ainews-f6d83',
    storageBucket: 'ainews-f6d83.firebasestorage.app',
    iosBundleId: 'com.newsbytebd.newsbyteBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB24LKrdGn6phkDuuB7tAGrH_iX-t3Qn7M',
    appId: '1:125810430014:web:824a273ad5695d932fc16f', // TODO: Update with macOS App ID
    messagingSenderId: '125810430014',
    projectId: 'ainews-f6d83',
    storageBucket: 'ainews-f6d83.firebasestorage.app',
    iosBundleId: 'com.newsbytebd.newsbyteBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB24LKrdGn6phkDuuB7tAGrH_iX-t3Qn7M',
    appId: '1:125810430014:web:824a273ad5695d932fc16f',
    messagingSenderId: '125810430014',
    projectId: 'ainews-f6d83',
    authDomain: 'ainews-f6d83.firebaseapp.com',
    storageBucket: 'ainews-f6d83.firebasestorage.app',
  );
}
